#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : file-roller
Version  : 43.0
Release  : 26
URL      : https://download.gnome.org/sources/file-roller/43/file-roller-43.0.tar.xz
Source0  : https://download.gnome.org/sources/file-roller/43/file-roller-43.0.tar.xz
Summary  : No detailed summary available
Group    : Development/Tools
License  : GPL-2.0
BuildRequires : buildreq-gnome
BuildRequires : buildreq-meson
BuildRequires : colord
BuildRequires : itstool
BuildRequires : json-glib-dev
BuildRequires : libarchive-dev
BuildRequires : libnotify-dev
BuildRequires : libportal-dev
BuildRequires : nautilus-dev
BuildRequires : pkgconfig(json-glib-1.0)
BuildRequires : pkgconfig(libarchive)
BuildRequires : pkgconfig(libhandy-1)
BuildRequires : pkgconfig(libnautilus-extension)
BuildRequires : pkgconfig(libnautilus-extension-4)
BuildRequires : pkgconfig(libnotify)
BuildRequires : pkgconfig(libportal)

%description
This file contains some instructions on how to use the command line arguments.
Extraction
----------

%prep
%setup -q -n file-roller-43.0
cd %{_builddir}/file-roller-43.0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1663965655
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=auto "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=auto "
CFLAGS="$CFLAGS" CXXFLAGS="$CXXFLAGS" LDFLAGS="$LDFLAGS" meson --libdir=lib64 --prefix=/usr --buildtype=plain   builddir
ninja -v -C builddir

%install
mkdir -p %{buildroot}/usr/share/package-licenses/file-roller
cp %{_builddir}/file-roller-%{version}/COPYING %{buildroot}/usr/share/package-licenses/file-roller/68c94ffc34f8ad2d7bfae3f5a6b996409211c1b1 || :
DESTDIR=%{buildroot} ninja -C builddir install

%files
%defattr(-,root,root,-)
